version: '3.5'

services:
  kurkkumopo-training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    container_name: kurkkumopo-training
    restart: unless-stopped
    volumes:
      - model:/src/model

  kurkkumopo-backend:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    container_name: kurkkumopo-backend
    restart: unless-stopped
    depends_on:
      - kurkkumopo-training
    volumes:
      - model:/src/model

  kurkkumopo-frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    container_name: kurkkumopo-frontend
    restart: unless-stopped
    depends_on:
      - kurkkumopo-backend

volumes:
  model:
